spring.application.name=E-Commerce REST API
#spring.datasource.username=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/user_management_db
spring.datasource.url=jdbc:postgresql://ep-sweet-poetry-amhpzc5w-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VXyP1INZ7qkW

#spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your-super-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000